name : Test Manual Workflow

on : 
    workflow_dispatch:
        inputs:
            Environment:
                description: " The environnement i needto deploy on"
                required : true
                default: '/dev'


jobs:
    manual_job:
        runs-on: ubuntu-latest
        steps:
           - name: Example
             run: echo "mon exemple"